# Generated by Django 2.2.3 on 2019-09-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absenHarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='absenTanggal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal1', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal1', to='absenHarian.absenHarian')),
                ('tanggal10', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal10', to='absenHarian.absenHarian')),
                ('tanggal11', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal11', to='absenHarian.absenHarian')),
                ('tanggal12', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal12', to='absenHarian.absenHarian')),
                ('tanggal13', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal13', to='absenHarian.absenHarian')),
                ('tanggal14', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal14', to='absenHarian.absenHarian')),
                ('tanggal15', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal15', to='absenHarian.absenHarian')),
                ('tanggal16', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal16', to='absenHarian.absenHarian')),
                ('tanggal17', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal17', to='absenHarian.absenHarian')),
                ('tanggal18', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal18', to='absenHarian.absenHarian')),
                ('tanggal19', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal19', to='absenHarian.absenHarian')),
                ('tanggal2', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal2', to='absenHarian.absenHarian')),
                ('tanggal20', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal20', to='absenHarian.absenHarian')),
                ('tanggal21', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal21', to='absenHarian.absenHarian')),
                ('tanggal22', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal22', to='absenHarian.absenHarian')),
                ('tanggal23', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal23', to='absenHarian.absenHarian')),
                ('tanggal24', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal24', to='absenHarian.absenHarian')),
                ('tanggal25', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal25', to='absenHarian.absenHarian')),
                ('tanggal26', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal26', to='absenHarian.absenHarian')),
                ('tanggal27', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal27', to='absenHarian.absenHarian')),
                ('tanggal28', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal28', to='absenHarian.absenHarian')),
                ('tanggal29', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal29', to='absenHarian.absenHarian')),
                ('tanggal3', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal3', to='absenHarian.absenHarian')),
                ('tanggal30', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal30', to='absenHarian.absenHarian')),
                ('tanggal31', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal31', to='absenHarian.absenHarian')),
                ('tanggal4', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal4', to='absenHarian.absenHarian')),
                ('tanggal5', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal5', to='absenHarian.absenHarian')),
                ('tanggal6', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal6', to='absenHarian.absenHarian')),
                ('tanggal7', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal7', to='absenHarian.absenHarian')),
                ('tanggal8', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal8', to='absenHarian.absenHarian')),
                ('tanggal9', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanggal9', to='absenHarian.absenHarian')),
            ],
            options={
                'db_table': 'absenTanggals',
            },
        ),
    ]
