# Generated by Django 2.2.3 on 2019-09-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
