# Generated by Django 2.2.3 on 2019-09-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameMapel', models.CharField(max_length=255, unique=True)),
                ('jurusan', models.CharField(choices=[('TKJ', 'TKJ'), ('MM', 'MM'), ('PDR', 'PDR'), ('OTKP', 'OTKP'), ('AKL', 'AKL'), ('PM', 'PM'), ('PS', 'PS')], max_length=255)),
                ('kelas', models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=100)),
            ],
            options={
                'db_table': 'mapels',
            },
        ),
    ]
