# Generated by Django 2.2.3 on 2019-09-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_siswa_nis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='file',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='siswa',
            name='no_telpon',
            field=models.IntegerField(default=0),
        ),
    ]
