# Generated by Django 2.2.3 on 2019-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_auto_20190921_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
