# Generated by Django 2.2.3 on 2019-09-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0005_auto_20190921_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='tanggal_lahir',
            new_name='tanggalLahir',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='tempat_lahir',
            new_name='tempatLahir',
        ),
    ]
