# Generated by Django 2.2.3 on 2019-09-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0006_auto_20190921_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='jenis_kelamin',
            new_name='jenisKelamin',
        ),
        migrations.RenameField(
            model_name='siswa',
            old_name='no_telpon',
            new_name='noTelepon',
        ),
    ]
