# Generated by Django 2.2.3 on 2019-09-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guru',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nip', models.IntegerField(default=0, unique=True)),
                ('fullName', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('alamat', models.TextField()),
                ('tempatLahir', models.CharField(max_length=255)),
                ('tanggalLahir', models.IntegerField(default=0)),
                ('Agama', models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Budha', 'Budha'), ('Hindu', 'Hindu'), ('Konghucu', 'Konghucu'), ('Lainnya', 'Lainnya')], max_length=255)),
                ('jenisKelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan'), ('Lainnya', 'Lainnya')], max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('noTelepon', models.IntegerField(default=0)),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('mapel1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapel1', to='mapel.mapel')),
                ('mapel2', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapel2', to='mapel.mapel')),
                ('mapel3', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapel3', to='mapel.mapel')),
                ('mapel4', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapel4', to='mapel.mapel')),
                ('mapel5', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapel5', to='mapel.mapel')),
            ],
            options={
                'db_table': 'gurus',
            },
        ),
    ]
