# Generated by Django 2.2.3 on 2019-09-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='absenHarian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jam1', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam2', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam3', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam4', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam5', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam6', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam7', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam8', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam9', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam10', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam11', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
                ('jam12', models.CharField(blank=True, choices=[('Masuk', 'Masuk'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], max_length=255, null=True)),
            ],
            options={
                'db_table': 'absenHarian',
            },
        ),
    ]
